spring.application.name=sqs-verkehrsapp
server.port=8080

#Autobahn Api
autobahn.api.base-url=https://verkehr.autobahn.de/o/autobahn

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/autobahn_safety_monitor}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Resilience4j Retry
resilience4j.retry.instances.autobahnApi.max-attempts=3
resilience4j.retry.instances.autobahnApi.wait-duration=1s

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.autobahnApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.autobahnApi.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.autobahnApi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.autobahnApi.sliding-window-size=10
